### ISSUE TITLE
Standby compass addresses incorrect

### ISSUE THREAD

**Issue by lesthegringo** [DCS-Skunkworks/Bort#12]
they should be 

Heading 0x1346
Pitch 0x1348
Bank 0x134a

according to Addresses.h

**Comment by charliefoxtwo** [comment]
![image](https://github.com/DCS-Skunkworks/Bort/assets/30303272/eff4d630-f7a8-4035-974c-ce8d45e962c9)
![image](https://github.com/DCS-Skunkworks/Bort/assets/30303272/9c67cb0a-f81e-4982-8163-1ece7390980c)
![image](https://github.com/DCS-Skunkworks/Bort/assets/30303272/e10acefe-8141-4a28-bd8a-42fad03bff81)

I just opened Bort and they seem correct to me. Is your Bort pointing to the correct json files? Go to `Menu > Select dcs-bios location` to verify

**Comment by charliefoxtwo** [comment]
Closed as bort appears to be working correctly - it just loads whatever is in the json files. If the json is different, then that's potentially an issue with an old bios install or old bios json files being present on the machine.
