### ISSUE TITLE
No latest release and no installation file (fixed)

### ISSUE THREAD

**Issue by Rambowski** [DCS-Skunkworks/Bort#18]
Gentlemen, how do I install the BORT? If I click on the "Latest release" there is nothing there and also no *.exe file into the Zip folder. I would highly appreciate your quick answer. Best regards!

**Comment by charliefoxtwo** [comment]
I just tested and it works fine for me?
![image](https://github.com/DCS-Skunkworks/Bort/assets/30303272/7051bb5c-943b-40c0-9188-8b5e6166e23e)
![image](https://github.com/DCS-Skunkworks/Bort/assets/30303272/b0b30863-b328-4ea2-8e90-36689ec44be5)
https://github.com/DCS-Skunkworks/Bort/releases/tag/v0.3.0

**Comment by Rambowski** [comment]
The latest release is now appearing and the link is functional again for me, thank you so much!
