### ISSUE TITLE
Bort not finding Json files

### ISSUE THREAD

**Issue by claas2k8** [DCS-Skunkworks/Bort#21]
hi I selected my path for the .json but its not registering.
E:\dcs-bios-master\Scripts\DCS-BIOS\doc\json

Unable to locate modules. Please set the path of the DCS-BIOS .json files from Menu > Select dcs-bios location.

Current path:
E:\dcs-bios-master\Scripts\DCS-BIOS\doc\json

**Comment by claas2k8** [comment]
sorry i was dumb with the first path, but the dcs saved games path does also not work (Unable to locate modules. Please set the path of the DCS-BIOS .json files from Menu > Select dcs-bios location.

Current path:
C:\Users\Claas\Saved Games\DCS\Scripts\DCS-BIOS\doc\json)

**Comment by charliefoxtwo** [comment]
Have you checked the folder to ensure that the json files are present in said folder?

**Comment by claas2k8** [comment]
no i havent, there are no files in the folder

**Comment by claas2k8** [comment]
ah sorry had to restart DCS 3 times but now i have files, sorry for the inconvinience
